#!/usr/bin/env bash
# scripts/bootstrap-versions.sh
# Autodiscover spec versions from submodules under sources/specification-vX.Y,
# generate per-version MkDocs overlays, produce versions.json, and write the
# /docs/swhid-specification/index.md selector page.
#
# Dependencies in CI: bash, git, jq, yq (mikefarah/yq), python (optional).
#
# ENV overrides:
#   LATEST_VERSION=vX.Y   # force which version is aliased as /latest
#   OVERWRITE_OVERLAYS=1  # re-generate overlays even if they exist
#   DEFAULT_DOCS_SUBDIR=Chapters  # where pages live inside each submodule
#   DEFAULT_SITE_NAME_PREFIX="SWHID Specification"
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
META_DIR="$ROOT/build/meta"
OVERLAYS_DIR="$ROOT/.monorepo-overlays"
SELECTOR_DIR="$ROOT/docs/swhid-specification"
DEFAULT_DOCS_SUBDIR="${DEFAULT_DOCS_SUBDIR:-Chapters}"
DEFAULT_SITE_NAME_PREFIX="${DEFAULT_SITE_NAME_PREFIX:-SWHID Specification}"

mkdir -p "$META_DIR" "$OVERLAYS_DIR" "$SELECTOR_DIR"

# 1) Discover versions from submodules like sources/specification-v1.0, v1.1, ...
mapfile -t found_dirs < <(find "$ROOT/sources" -maxdepth 1 -type d -name 'specification-v*' | sort -V || true)
if ((${#found_dirs[@]} == 0)); then
  echo "❌ No 'sources/specification-v*' directories found."
  echo "   This is expected if submodules are not initialized yet."
  echo "   Run 'git submodule update --init --recursive' first."
  exit 0
fi

versions=()
for d in "${found_dirs[@]}"; do
  base="$(basename "$d")"              # e.g., specification-v1.1
  ver="${base#specification-}"         # -> v1.1
  # guard: ensure matches vN.N pattern
  if [[ "$ver" =~ ^v[0-9]+\.[0-9]+$ ]]; then
    versions+=("$ver")
  else
    echo "⚠️  Skipping '$base' (does not look like vX.Y)."
  fi
done

# Add dev version if main specification directory exists
if [ -d "$ROOT/sources/specification" ]; then
  echo "  • Adding dev version from main specification directory"
  versions+=("dev")
else
  echo "⚠️  Main specification directory not found, skipping dev version"
fi

if ((${#versions[@]} == 0)); then
  echo "❌ No versions discovered after filtering."
  exit 0
fi

# Sort semver (simple -V works for vN.N)
IFS=$'\n' versions=($(sort -V <<<"${versions[*]}")); unset IFS

# Compute latest (exclude dev from being latest)
tagged_versions=()
for v in "${versions[@]}"; do
  if [[ "$v" != "dev" ]]; then
    tagged_versions+=("$v")
  fi
done

if ((${#tagged_versions[@]} > 0)); then
  latest="${LATEST_VERSION:-${tagged_versions[-1]}}"
  if ! printf '%s\n' "${tagged_versions[@]}" | grep -qx "$latest"; then
    echo "⚠️  LATEST_VERSION='$latest' not in tagged versions; falling back to max."
    latest="${tagged_versions[-1]}"
  fi
else
  echo "⚠️  No tagged versions found, using first available version as latest"
  latest="${versions[0]}"
fi
echo "→ Discovered versions: ${versions[*]}"
echo "→ Latest: $latest"

# 2) Write versions.json (for CI) and the selector page
versions_json="$META_DIR/versions.json"
{
  printf '{\n  "versions": [\n'
  for i in "${!versions[@]}"; do
    v="${versions[$i]}"
    sep=$([ "$i" -lt $(( ${#versions[@]} - 1 )) ] && echo "," || echo "")
    printf '    "%s"%s\n' "$v" "$sep"
  done
  printf '  ],\n  "latest": "%s"\n}\n' "$latest"
} > "$versions_json"
echo "📝 Wrote $versions_json"
cat "$versions_json" || true

selector_md="$SELECTOR_DIR/index.md"
{
  echo "# SWHID Specification"
  echo
  echo "## Available versions"
  for (( idx=${#versions[@]}-1 ; idx>=0 ; idx-- )); do
    v="${versions[$idx]}"
    if [[ "$v" == "$latest" ]]; then
      echo "- [${v} (latest)](../swhid-specification/${v}/)"
    else
      echo "- [${v}](../swhid-specification/${v}/)"
    fi
  done
  echo
  echo "- [latest](../swhid-specification/latest/)"
} > "$selector_md"
echo "📝 Wrote $selector_md"

# 2.5) Generate latest redirect page
latest_redirect="$SELECTOR_DIR/latest/index.md"
mkdir -p "$(dirname "$latest_redirect")"
{
  echo "---"
  echo "template: redirect.html"
  echo "redirect_url: ../${latest}/"
  echo "---"
  echo "<!-- Redirect to latest (generated by bootstrap script) -->"
} > "$latest_redirect"
echo "📝 Wrote $latest_redirect"

# 2.6) Generate CSS to hide top-level nav tabs for individual versions
HIDE_CSS="docs/assets/stylesheets/hide-version-tabs.css"
echo "/* auto-generated by bootstrap-versions.sh */" > "$HIDE_CSS"
for v in "${versions[@]}"; do
  # Skip "latest" alias: it's not a real top-level tab
  [ "$v" = "latest" ] && continue
  # Hide top-level tab anchors that point to version roots
  echo ".md-tabs__link[href\$=\"/swhid-specification/${v}/\"] { display: none !important; }" >> "$HIDE_CSS"
done
echo "📝 Wrote $HIDE_CSS"

# 3) Generate configuration files from templates
echo "  • Generating configuration files from templates..."
python3 "$ROOT/scripts/generate-config.py"

# 4) Generate nav.yml with all discovered versions
nav_yml="$ROOT/nav.yml"
echo "📝 Generating navigation file: $nav_yml"

{
  echo "# Auto-generated navigation file"
  echo "# Do not edit manually - run scripts/bootstrap-versions.sh to regenerate"
  echo ""
  echo "- Home: index.md"
  echo "- Specification: '!include .monorepo-overlays/spec-${latest}.mkdocs.yml'"
  for v in "${versions[@]}"; do
    if [[ "$v" != "$latest" && "$v" != "dev" ]]; then
      echo "- \"${v}\": '!include .monorepo-overlays/spec-${v}.mkdocs.yml'"
    fi
  done
  # Always include dev version in navigation (will be hidden with CSS)
  if printf '%s\n' "${versions[@]}" | grep -q "^dev$"; then
    echo "- \"dev\": '!include .monorepo-overlays/spec-dev.mkdocs.yml'"
  fi
  echo "- \"Implementations\": implementations.md"
  echo "- Governance: '!include sources/governance/mkdocs.yml'"
  echo "- FAQ: faq.md"
  echo "- News:"
  echo "  - \"All news\": news/index.md"
  echo "  - \"SWHID standardized as ISO/IEC 18670\": news/2025-04-23-swhid-standardized-as-iso-iec-18670.md"
  echo "  - \"Second version of SWHID Publicly Available Specification\": news/2023-11-06-second-version-of-swhid-publicly-available-specification.md"
  echo "  - \"First version of SWHID Publicly Available Specification\": news/2023-06-23-first-version-of-swhid-publicly-available-specification.md"
  echo "  - \"Kickoff of the SWHID Working group\": news/2023-03-27-kickoff-of-the-swhid-working-group.md"
  echo "  - \"SWHID.org goes live\": news/2022-09-07-swhid-org-goes-live.md"
  echo "  - \"Decision to start the SWHID normalization process\": news/2022-01-20-decision-to-start-the-swhid-normalization-process.md"
  echo "- Tags: tags/index.md"
  echo "- Publications: publications.md"
  echo "- Core Team: coreteam.md"
} > "$nav_yml"

echo "✅ Generated $nav_yml with ${#versions[@]} versions"

# 5) Merge nav.yml into mkdocs.yml
echo "📝 Merging navigation into mkdocs.yml..."
if [[ -f "$ROOT/scripts/merge-nav.py" ]]; then
    python3 "$ROOT/scripts/merge-nav.py"
else
    echo "⚠️  merge-nav.py not found, skipping navigation merge"
fi

# 6) Generate tags page
echo "  • Generating tags page..."
if [ -f "$ROOT/scripts/generate-tags.py" ]; then
    python3 "$ROOT/scripts/generate-tags.py"
else
    echo "⚠️  generate-tags.py not found, skipping tags page generation"
fi

# 6.5) Generate implementations page
echo "  • Generating implementations page..."
if [ -f "$ROOT/scripts/generate-implementations.py" ]; then
    python3 "$ROOT/scripts/generate-implementations.py"
else
    echo "⚠️  generate-implementations.py not found, skipping implementations page generation"
fi

# 7) Expose outputs (for GitHub Actions)
if [[ "${GITHUB_OUTPUT:-}" != "" ]]; then
  echo "versions=$(jq -rc '.versions' "$versions_json")" >> "$GITHUB_OUTPUT"
  echo "latest=$(jq -r '.latest' "$versions_json")" >> "$GITHUB_OUTPUT"
fi

echo "✅ bootstrap-versions.sh finished."
echo "→ Versions discovered: ${versions[*]} (latest: ${latest})"